name = "url2mda"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat"]


# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Browser"] # Array of new classes

[[kv_namespaces]]
binding= "MDA_CACHE"
id = "d8976411926248238493989e7ac09dd9"
preview_id = "c92ff41b8f074a7ab5f7aa3bb711a38d" 

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 30, period = 60 } # 10 requests per 60 seconds


[ai]
binding = "AI"

# Environment Variables
[vars]
# BACKEND_URL = "YOUR_BACKEND_URL" # Replace with your actual backend URL if needed
# Secrets like BACKEND_SECURITY_TOKEN, OPENAI_API_KEY, REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET
# should be set using `wrangler secret put <SECRET_NAME>` in your Cloudflare environment.
# They will be available as environment variables within the worker.
