export const KEEP_BROWSER_ALIVE_IN_SECONDS = 60;
export const TEN_SECONDS = 10000;
export const SIMPLE_CONTENT_MAX_LENGTH = 10000;
export const TWITTER_TIMEOUT = 10000;
export const LOAD_MORE_TWEETS_SCROLL_AMOUNT = 2000;
export const LOAD_MORE_TWEETS_SCROLL_DELAY = 2000; 